version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: h0te1/kittygram_backend:latest
    volumes:
     - static:/backend_static
     - media:/media
    env_file: .env

  frontend:
    env_file: .env
    image: h0te1/kittygram_frontend:latest
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static

  gateway:
    image: h0te1/kittygram_gateway:latest
    env_file: .env
    ports:
      - 9000:80
    volumes:
     - static:/staticfiles
     - media:/media
